# =========================
# Application Info
# =========================
spring.application.name=TaskHub


# =========================
# Database Configurations
# =========================

# --- H2 In-Memory Database (local testing) ---
#spring.datasource.url=jdbc:h2:mem:taskhub;DB_CLOSE_DELAY=-1;MODE=MySQL
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
## HikariCP Connection Pool
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.idle-timeout=30000
#spring.datasource.hikari.max-lifetime=600000
#
## JPA / Hibernate (H2)
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
#
## H2 Console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console


# --- PostgreSQL Database (dev/prod) ---
spring.main.banner-mode=off
spring.datasource.url=jdbc:postgresql://localhost:5432/TaskHub
spring.datasource.username=postgres
spring.datasource.password=Sandeep@2002
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate (PostgreSQL)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# =========================
# JWT Configuration
# =========================
spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=3600000



# Debug Logging
logging.level.com.aithinkers.TaskHub.jwt=DEBUG
logging.level.com.aithinkers.TaskHub.config=DEBUG
logging.level.org.springframework.security=DEBUG

# Thymeleaf
spring.thymeleaf.cache=false

