spring.application.name=TaskHub

spring.main.banner-mode=off

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/TaskHub
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update  
spring.jpa.show-sql=true

# JWT Configuration
spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=3600000

# Debug Logging
logging.level.com.aithinkers.TaskHub.jwt=DEBUG
logging.level.com.aithinkers.TaskHub.config=DEBUG
logging.level.org.springframework.security=DEBUG


# Thymeleaf
spring.thymeleaf.cache=false

